---
title: ESS330-intro-methods
authors:
  - name: Megan Hoover
    affiliation: Colorado State University
    roles: writing
    corresponding: true
    authors:
  - name: Lilly Zapalac
    affiliation: Colorado State University
    roles: writing
  - name: Tessa 
    affiliation: Colorado State University
    roles: Writing
bibliography: references.bib
---

## Section
This is a simple placeholder for the manuscript's main document [@knuth84].

## Karenia Brevis Harmful Algal Blooms


#Introduction, Background, and Motivation

Problem Overview:  
Karenia Algal blooms are commonly known as the red tide and are toxic blooms that produce brevetoxins, a potent neurotoxin that can cause repository problems in humans. It can also accumulate in shellfish tissues that cause Neurotoxic Shellfish Poisoning (NSP) when ingested. This harmful brevetoxin producing algae, makes it hard to detect due to it being tasteless, having no odor, and remaining stable in hot or acidic environments. The Karenia algae doesn’t have a specific growing season, which makes it harder to predict when it will occur. The blooms are most present in the summer and fall but can also be problematic in other seasons as well. There isn’t currently a clear relationship of what causes this harmful algal bloom, but there are ongoing studies that are trying to understand how different nutrients affect or initiate the bloom due to high cell concentrations being mainly found close to shores (https://hab.whoi.edu/species/species-by-name/karenia/). 

Data overview:  
The data we’re using to better understand the red tide causing blooms, is provided by NOAA. The excel sheets provided are from sites in Florida and Texas and contain data that span many decades. The same sites in both of the states have been tested on repeatedly throughout time, which will help to show patterns and relationships, if there’s any. It will also help to compare the different states and the trends they do or don’t have.  Location columns show the name of the water body that the Karenia Brevis algal are found and which city they’re found off. There’s also a column for latitude, longitude, date, time of the extraction, depth of water measures, ranking of algal cells per liter, salinity of the water in parts per trillion, water temperature measured in degrees Celsius, and the object id where the sites are being tested at. Even though there’s a lot of variables, there’s a lot of missing data for some columns.

The NOAA data will allow us to compare Texas and Florida coastlines with different variables to see which variables have the most impact on the growth of Karenia brevis, causing the toxic red tides. This will allow us to determine if Texas or Florida is more susceptible to red tides. Since the location is also provided in the excel sheets, we’ll be able to make a map of areas to show different intensities of algae blooms, and then we’ll be able to determine which state and region have more intense red tides. We can also make a graph with dates and the number of algae cells in the water within both states and determine if the algae blooms have been increasing or decreasing in intensity and frequency. Knowing this information can help to inform policy makers and local communities about causes of this harmful algae species, and how to implement changes to decrease the blooms. 

